name: UKHealthCamp
markdown: kramdown
highlighter: null
sass:
    style: compressed
show_alert: true
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]